### ISSUE TITLE
Make Slot Machine

### ISSUE THREAD

**Issue by holdenxo** [holdenxo/firstcollabgame#1]
Add a falling slot machine, art/programming needed. gives negative score or positive. (give %)

**Comment by isaac-andi** [comment]
![slotmachine-v1](https://github.com/user-attachments/assets/282a1201-36d7-431d-8099-1ac83c3531d3)

**Comment by isaac-andi** [comment]
![slotmachine-v2](https://github.com/user-attachments/assets/5ecc2344-5652-4da5-9f84-ab185255e360)
added shading
