### ISSUE TITLE
Add Poker Chips

### ISSUE THREAD

**Issue by holdenxo** [holdenxo/firstcollabgame#3]
Add falling poker chips. these should be the normal dropper/coins, make them spin if possible, if not no problem

**Comment by isaac-andi** [comment]
Ive made two versions of poker chips- tell me if this style is good. If so, I can make a few frames of each so they can spin

![red-pokerchip-v1](https://github.com/user-attachments/assets/f2ece0f0-0cce-42a8-ba8b-474de20d5e59)
![green-pokerchip-v1](https://github.com/user-attachments/assets/5ec45f36-66ee-4596-b6cf-f9b00dae3327)

**Comment by holdenxo** [comment]
both look good
